import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../shared/theme/theme_ext.dart';
import '../../../../shared/widgets/custom_button.dart';
import '../../domain/entities/student_entity.dart';
import '../bloc/student_bloc.dart';
import '../bloc/student_event.dart';
import '../bloc/student_state.dart';

class AddStudentForm extends StatefulWidget {
  final String groupId;
  final StudentEntity? student;

  const AddStudentForm({super.key, required this.groupId, this.student});

  @override
  State<AddStudentForm> createState() => _AddStudentFormState();
}

class _AddStudentFormState extends State<AddStudentForm> {
  late final TextEditingController _firstNameController;
  late final TextEditingController _lastNameController;
  late final TextEditingController _roomNumberController;
  late final TextEditingController _classNameController;

  @override
  void initState() {
    super.initState();
    _firstNameController = TextEditingController(
      text: widget.student?.firstName ?? '',
    );
    _lastNameController = TextEditingController(
      text: widget.student?.lastName ?? '',
    );
    _roomNumberController = TextEditingController(
      text: widget.student?.roomNumber ?? '',
    );
    _classNameController = TextEditingController(
      text: widget.student?.className ?? '',
    );
  }

  @override
  void dispose() {
    _firstNameController.dispose();
    _lastNameController.dispose();
    _roomNumberController.dispose();
    _classNameController.dispose();
    super.dispose();
  }

  void _submit(BuildContext context) {
    if (_firstNameController.text.trim().isEmpty ||
        _lastNameController.text.trim().isEmpty) {
      return;
    }

    final editedStudent = StudentEntity(
      id: widget.student?.id ?? '', // Will be generated by Supabase if empty
      firstName: _firstNameController.text.trim(),
      lastName: _lastNameController.text.trim(),
      roomNumber: _roomNumberController.text.trim(),
      className: _classNameController.text.trim(),
      groupId: widget.groupId,
    );

    if (widget.student != null) {
      context.read<StudentBloc>().add(UpdateStudent(editedStudent));
    } else {
      context.read<StudentBloc>().add(AddStudent(editedStudent));
    }
  }

  bool _isFormValid() {
    return _firstNameController.text.trim().isNotEmpty &&
        _lastNameController.text.trim().isNotEmpty;
  }

  @override
  Widget build(BuildContext context) {
    return BlocListener<StudentBloc, StudentState>(
      listener: (context, state) {
        if (state is StudentsLoaded) {
          Navigator.of(context).pop();
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                widget.student != null ? 'Élève mis à jour' : 'Élève ajouté',
              ),
              backgroundColor: context.colorScheme.primary,
            ),
          );
        } else if (state is StudentsError) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(state.message),
              backgroundColor: context.colorScheme.error,
            ),
          );
        }
      },
      child: Padding(
        padding: EdgeInsets.only(
          bottom: MediaQuery.of(context).viewInsets.bottom,
          left: 16,
          right: 16,
          top: 24,
        ),
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text(
                widget.student != null ? 'Modifier l\'élève' : 'Nouvel Élève',
                style: context.textTheme.headlineSmall?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 24),
              Row(
                children: [
                  Expanded(
                    child: TextField(
                      controller: _firstNameController,
                      autofocus: true,
                      decoration: InputDecoration(
                        labelText: 'Prénom',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                        filled: true,
                        fillColor: context.colorScheme.surface,
                      ),
                      onChanged: (_) => setState(() {}),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: TextField(
                      controller: _lastNameController,
                      decoration: InputDecoration(
                        labelText: 'Nom',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                        filled: true,
                        fillColor: context.colorScheme.surface,
                      ),
                      onChanged: (_) => setState(() {}),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: TextField(
                      controller: _roomNumberController,
                      decoration: InputDecoration(
                        labelText: 'Chambre (Optionnel)',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                        filled: true,
                        fillColor: context.colorScheme.surface,
                      ),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: TextField(
                      controller: _classNameController,
                      decoration: InputDecoration(
                        labelText: 'Classe (Optionnel)',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                        filled: true,
                        fillColor: context.colorScheme.surface,
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 32),
              BlocBuilder<StudentBloc, StudentState>(
                builder: (context, state) {
                  final isLoading = state is StudentsLoading;
                  return CustomButton(
                    text: widget.student != null ? 'Mettre à jour' : 'Ajouter',
                    onPressed: !_isFormValid() || isLoading
                        ? null
                        : () => _submit(context),
                    isLoading: isLoading,
                  );
                },
              ),
              const SizedBox(height: 24),
            ],
          ),
        ),
      ),
    );
  }
}
