import '../../domain/entities/attendance_archive_entity.dart';

class AttendanceArchiveModel extends AttendanceArchiveEntity {
  const AttendanceArchiveModel({
    required super.id,
    required super.studentId,
    required super.groupId,
    required super.storedLastName,
    required super.storedFirstName,
    required super.storedClassName,
    required super.storedRoomNumber,
    required super.periodLabel,
    required super.checkDate,
    required super.status,
    super.note,
    required super.archiveDate,
    super.checkInTime,
    super.checkOutTime,
  });

  factory AttendanceArchiveModel.fromJson(Map<String, dynamic> json) {
    return AttendanceArchiveModel(
      id: json['id'] as String,
      studentId:
          json['student_id'] as String? ??
          '', // Could be null if deleted, we fallback empty
      groupId: json['group_id'] as String? ?? '',
      storedLastName: json['stored_last_name'] as String,
      storedFirstName: json['stored_first_name'] as String,
      storedClassName: json['stored_class_name'] as String,
      storedRoomNumber: json['stored_room_number'] as String,
      periodLabel: json['period_label'] as String? ?? 'Inconnu',
      checkDate: DateTime.parse(json['check_date'] as String),
      status: json['status'] as String,
      note: json['note'] as String?,
      archiveDate: DateTime.parse(json['archive_date'] as String),
      checkInTime: json['check_in_time'] != null
          ? DateTime.tryParse(json['check_in_time'] as String)
          : null,
      checkOutTime: json['check_out_time'] != null
          ? DateTime.tryParse(json['check_out_time'] as String)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'student_id': studentId,
      'group_id': groupId,
      'stored_last_name': storedLastName,
      'stored_first_name': storedFirstName,
      'stored_class_name': storedClassName,
      'stored_room_number': storedRoomNumber,
      'period_label': periodLabel,
      'check_date':
          "${checkDate.year}-${checkDate.month.toString().padLeft(2, '0')}-${checkDate.day.toString().padLeft(2, '0')}",
      'status': status,
      'note': note,
      if (checkInTime != null)
        'check_in_time': checkInTime!.toUtc().toIso8601String(),
      if (checkOutTime != null)
        'check_out_time': checkOutTime!.toUtc().toIso8601String(),
      // 'id' and 'archive_date' are generated by Supabase
    };
  }
}
