import '../../domain/entities/student_entity.dart';

/// Data model representing a Student, handling serialization.
class StudentModel extends StudentEntity {
  const StudentModel({
    required super.id,
    required super.firstName,
    required super.lastName,
    required super.roomNumber,
    required super.className,
    required super.groupId,
  });

  /// Creates a StudentModel from a JSON map (Supabase).
  factory StudentModel.fromJson(Map<String, dynamic> json) {
    return StudentModel(
      id: json['id'] as String,
      firstName: json['first_name'] as String,
      lastName: json['last_name'] as String,
      roomNumber: json['room_number'] as String,
      className: json['class_name'] as String,
      groupId: json['group_id'] as String,
    );
  }

  /// Converts a StudentEntity to a JSON map for Supabase insertion/updates.
  /// (id is usually generated by Supabase so we omit it for creation).
  Map<String, dynamic> toJson() {
    return {
      'first_name': firstName,
      'last_name': lastName,
      'room_number': roomNumber,
      'class_name': className,
      'group_id': groupId,
    };
  }
}
